### ISSUE TITLE
Try to use GONE and VISIBLE to control the View visibility

### ISSUE THREAD

**Issue by LinXiaoTao** [krishnarb3/Popview-Android#4]
I think the use of VISIBLE and GONE, better able to repeat. Use the View for instance can be repeated in between the two View appear and disappear

This is a machine translation --!

**Comment by krishnarb3** [comment]
View.GONE to my knowledge does the same action as ViewGroup.removeView(view).
Is there any advantage to using it?
View.INVISIBLE might be useful for just popping the view .
I'll try to change it.
Feel free to send a Pull Request :blush:

**Comment by LinXiaoTao** [comment]
Let have disappeared, come back...

**Comment by LinXiaoTao** [comment]
I use the one of your tools, in my project
PopUtils. java
![image](https://cloud.githubusercontent.com/assets/19836925/16711574/735ef538-4695-11e6-8727-8e650117e4b0.png)

**Comment by krishnarb3** [comment]
That's very nice :blush: 
Credits to [https://github.com/tyrantgit/ExplosionField](url)
